name = "PET"
uuid = "818149cd-5caa-400d-8d3a-cc13d265cce7"
version = "1.0.0-DEV"
authors = ["Joseph A.P. POLLACCO"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.10.15"
Configurations = "0.17.6"
DataFrames = "1.8.1"
Dates = "1.11.0"
TOML = "1.0.3"
Tables = "1.12.1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
